radeon_dri2_create_buffer2: remove unused variable tiling
The code that used this was removed in commit 615033f2b5e3817e335e9d
Recent versions of clang flag this:
radeon_dri2.c:114:14: error: variable 'tiling' set but not used
 [-Werror,-Wunused-but-set-variable]
    uint32_t tiling = 0;
             ^

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-ati/-/merge_requests/19>