RADEONInit3DEngineInternal: remove unused variable gb_tile_config
Prior to commit 18d5ae3bd9075ac1a2ee21b071ac133e2e634b62
gb_tile_config was used in OUTREG(R300_GB_TILE_CONFIG, gb_tile_config);
but since then it's unused, and is flagged by recent clang versions:

radeon_accel.c:209:14: error: variable 'gb_tile_config' set but not used
 [-Werror,-Wunused-but-set-variable]
    uint32_t gb_tile_config, vap_cntl;
             ^

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-ati/-/merge_requests/19>