configure: Include xorg-server.h before glamor.h
glamor.h cannot be included without first including xorg-server.h, this also
applies to including it from configure snippets.

Without this the configure glamor checks fail on systems with the latest
glibc, throwing this error:

In file included from /usr/include/xorg/misc.h:115:0,
                 from /usr/include/xorg/screenint.h:50,
                 from /usr/include/xorg/scrnintstr.h:50,
                 from /usr/include/xorg/glamor.h:32,
                 from conftest.c:61:
/usr/include/xorg/os.h:579:2: error: expected identifier or '(' before
'__exten
 strndup(const char *str, size_t n);
  ^

This is caused by HAVE_STRNDUP not being set (it is set from xorg-server.h),
causing os.h to redefine it.

Signed-off-by: Hans de Goede <hdegoede@redhat.com>